<?php
require_once __DIR__.'/../includes/config.php';
require_once __DIR__.'/../includes/functions.php';

// Check if the user is logged in and is a superadmin
if (!is_logged_in() || $_SESSION['role'] !== 'superadmin') {
    redirect('../login.php?error=unauthorized');
}

$message = '';
$message_type = ''; // For styling success/error messages
$generated_codes = [];

// Fetch all existing codes
$all_codes = [];
$query = "SELECT sc.*, u.username as generated_by_username 
          FROM special_codes sc 
          LEFT JOIN users u ON sc.generated_by = u.id 
          ORDER BY sc.created_at DESC";
$result = $mysqli->query($query);
if ($result) {
    while ($row = $result->fetch_assoc()) {
        $all_codes[] = $row;
    }
}

// Handle code download
if (isset($_GET['download']) && $_GET['download'] === 'true') {
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="registration_codes.csv"');
    
    $output = fopen('php://output', 'w');
    fputcsv($output, ['Code', 'Role', 'Specialization', 'Generated By', 'Created Date', 'Expiry Date', 'Status']);
    
    foreach ($all_codes as $code) {
        $status = strtotime($code['expiry_date']) < time() ? 'Expired' : 'Active';
        fputcsv($output, [
            $code['code'],
            $code['role'],
            $code['specialization'],
            $code['generated_by_username'],
            $code['created_at'],
            $code['expiry_date'],
            $status
        ]);
    }
    
    fclose($output);
    exit();
}

// Handle code deletion
if (isset($_GET['delete']) && !empty($_GET['delete'])) {
    $code_to_delete = trim($_GET['delete']);
    $stmt = $mysqli->prepare("DELETE FROM special_codes WHERE code = ?");
    $stmt->bind_param("s", $code_to_delete);
    
    if ($stmt->execute()) {
        $message = "Code successfully deleted.";
        $message_type = 'success';
    } else {
        $message = "Error deleting code: " . $mysqli->error;
        $message_type = 'error';
    }
    $stmt->close();
    
    // Redirect to remove the delete parameter from URL
    redirect('register_codes.php');
}

// Define valid roles
$valid_roles = ['student', 'technician', 'faculty', 'nonteaching', 'outsourced_vendor'];
$categories = ['mess', 'carpenter', 'wifi', 'housekeeping', 'plumber', 'electrician', 'laundry', 'ac'];

if (isset($_SESSION['message'])) {
    $message = $_SESSION['message'];
    $message_type = $_SESSION['message_type'];
    unset($_SESSION['message'], $_SESSION['message_type']);
}

if (isset($_SESSION['generated_codes'])) {
    $generated_codes = $_SESSION['generated_codes'];
    unset($_SESSION['generated_codes']);
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $generated_by = $_SESSION['user_id'];
    $role = isset($_POST['role']) ? trim($_POST['role']) : '';
    $expiry_days = isset($_POST['expiry_days']) ? intval($_POST['expiry_days']) : 30;
    $expiry_date = date('Y-m-d H:i:s', strtotime("+{$expiry_days} days"));

    // Validate role
    if (!in_array($role, $valid_roles)) {
        $message = 'Please select a valid user type.';
        $message_type = 'error';
    }
    // Validate expiry days
    elseif ($expiry_days <= 0 || $expiry_days > 365) {
        $message = 'Please enter a valid expiry period (1-365 days).';
        $message_type = 'error';
    } else {
        try {
            $mysqli->begin_transaction();

            $specialization = null;
            // Only require specialization for roles other than technician (future-proofing)
            if ($role !== 'technician' && $role !== 'student' && $role !== 'faculty' && $role !== 'nonteaching' && $role !== 'outsourced_vendor') {
                $specialization = isset($_POST['specialization']) ? trim($_POST['specialization']) : null;
            }
            // For technician, always set specialization to null

            // Generate single code
            $code = generate_simple_code($role, $specialization);
            $stmt = $mysqli->prepare("INSERT INTO special_codes (code, role, specialization, generated_by, expiry_date) VALUES (?, ?, ?, ?, ?)");
            if (!$stmt) {
                throw new Exception('Prepare failed: ' . $mysqli->error);
            }
            $stmt->bind_param("sssis", $code, $role, $specialization, $generated_by, $expiry_date);
            if ($stmt->execute()) {
                $generated_codes[] = [
                    'code' => $code,
                    'role' => $role,
                    'specialization' => $specialization,
                    'expiry_date' => $expiry_date
                ];
                $stmt->close();
                $mysqli->commit();
                $_SESSION['generated_codes'] = $generated_codes;
                redirect('register_codes.php'); // PRG pattern
                exit;
            } else {
                throw new Exception('Execute failed: ' . $stmt->error);
            }
            $stmt->close();

            $mysqli->commit();
        } catch (Exception $e) {
            $mysqli->rollback();
            $message = 'An error occurred while generating code: ' . $e->getMessage();
            $message_type = 'error';
            error_log("Code generation error: " . $e->getMessage());
        }
    }
}

// Improved function to generate simple, easy-to-input codes
function generate_simple_code($role, $specialization = null) {
    global $mysqli;
    
    // Simple format: XXXX where XXXX is 4 characters
    // Use only uppercase letters and numbers, excluding confusing characters
    
    $characters = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // No 0,1,I,O
    
    do {
        $code = '';
        for ($i = 0; $i < 4; $i++) {
            $code .= $characters[random_int(0, strlen($characters) - 1)];
        }
        
        // Check if code already exists
        $stmt = $mysqli->prepare("SELECT COUNT(*) FROM special_codes WHERE code = ?");
        $stmt->bind_param("s", $code);
        $stmt->execute();
        $result = $stmt->get_result();
        $exists = $result->fetch_row()[0] > 0;
        $stmt->close();
    } while ($exists);
    
    return $code;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Registration Codes</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        /* Enhanced green theme for header */
        .nav-green-theme {
            background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
            border-bottom: 2px solid #bbf7d0;
            box-shadow: 0 2px 8px rgba(34, 197, 94, 0.1);
        }
        
        .nav-green-theme .text-slate-900 {
            color: #166534 !important;
        }
        
        .nav-green-theme .text-slate-500 {
            color: #16a34a !important;
        }
        
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            background: #f5f5f5;
            min-height: 100vh;
            padding: 1rem;
            color: #333;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        }
        
        .header {
            background: #4a5568;
            color: white;
            padding: 1.5rem;
            border-radius: 8px 8px 0 0;
        }
        
        .header h2 {
            font-size: 1.5rem;
            font-weight: 600;
        }
        
        .content {
            padding: 1.5rem;
        }
        
        .message {
            padding: 1rem;
            margin-bottom: 1.5rem;
            border-radius: 6px;
            font-weight: 500;
        }
        
        .message.success {
            background: #e6f4ea;
            color: #1e7e34;
        }
        
        .message.error {
            background: #fde8e8;
            color: #c53030;
        }
        
        .info-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 1.25rem;
            margin-bottom: 1.5rem;
        }
        
        .info-card h4 {
            margin-bottom: 0.75rem;
            color: #2d3748;
            font-size: 1rem;
            font-weight: 600;
        }
        
        .info-card ul {
            margin: 0;
            padding-left: 1.25rem;
        }
        
        .info-card li {
            margin: 0.5rem 0;
            color: #4a5568;
        }
        
        .form-section {
            background: white;
            padding: 1.5rem;
            border-radius: 6px;
            border: 1px solid #e2e8f0;
        }
        
        .form-section h3 {
            color: #2d3748;
            font-size: 1.25rem;
            font-weight: 600;
            margin-bottom: 1.5rem;
        }
        
        .form-group {
            margin-bottom: 1rem;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: 500;
            color: #4a5568;
        }
        
        .form-group input,
        .form-group select {
            width: 100%;
            padding: 0.625rem;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            font-size: 0.875rem;
        }
        
        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: #4a5568;
        }
        
        .form-group small {
            color: #718096;
            font-size: 0.75rem;
            margin-top: 0.25rem;
            display: block;
        }
        
        .btn {
            padding: 0.625rem 1rem;
            background: #4a5568;
            color: white;
            text-decoration: none;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            font-size: 0.875rem;
            font-weight: 500;
            display: inline-block;
        }
        
        .btn:hover {
            background: #2d3748;
        }
        
        .btn-secondary {
            background: #718096;
        }
        
        .btn-success {
            background: #38a169;
        }
        
        .btn-danger {
            background: #e53e3e;
        }
        
        .codes-list {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 1.25rem;
            margin-bottom: 1.5rem;
        }
        
        .code-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
        }
        
        .code-item {
            background: white;
            border: 1px solid #e2e8f0;
            border-radius: 4px;
            padding: 1rem;
        }
        
        .code-value {
            font-family: 'Courier New', monospace;
            font-size: 1.125rem;
            font-weight: bold;
            color: #2d3748;
            background: #f8fafc;
            padding: 0.5rem;
            border-radius: 4px;
            text-align: center;
            margin-bottom: 0.75rem;
            border: 1px solid #e2e8f0;
        }
        
        .code-info {
            display: grid;
            gap: 0.25rem;
            font-size: 0.875rem;
        }
        
        .code-info div {
            display: flex;
            justify-content: space-between;
        }
        
        .all-codes {
            margin-top: 1.5rem;
        }
        
        .all-codes h3 {
            color: #2d3748;
            margin-bottom: 1rem;
            font-size: 1.25rem;
            font-weight: 600;
        }
        
        .actions-row {
            display: flex;
            gap: 1rem;
            align-items: center;
            margin-bottom: 1rem;
            flex-wrap: wrap;
        }
        
        .table-container {
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            overflow-x: auto;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }
        
        th, td {
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
        }
        
        th {
            background: #f8fafc;
            font-weight: 600;
            color: #2d3748;
        }
        
        tr:hover {
            background-color: #f8fafc;
        }
        
        .status-active {
            color: #38a169;
            font-weight: 500;
        }
        
        .status-expired {
            color: #e53e3e;
            font-weight: 500;
        }
        
        .code-cell {
            font-family: 'Courier New', monospace;
            font-weight: bold;
            color: #2d3748;
        }
        
        .back-btn {
            text-align: center;
            margin-top: 1.5rem;
        }
        
        @media (max-width: 768px) {
            /* Force mobile layout */
            body {
                overflow-x: hidden;
                padding: 0.5rem;
                padding-top: 5rem; /* Add space for hamburger menu */
            }
            
            .mobile-nav {
                flex-direction: column !important;
                height: auto !important;
                padding: 1rem 0 !important;
                gap: 1rem !important;
                position: relative !important;
                z-index: 10 !important;
            }
            
            .mobile-nav .flex {
                flex-direction: column !important;
                gap: 1rem !important;
                align-items: center !important;
                width: 100% !important;
            }
            
            .mobile-nav .space-x-4 {
                flex-direction: column !important;
                gap: 0.75rem !important;
                width: 100% !important;
                align-items: center !important;
                display: flex !important;
            }
            
            .mobile-nav .space-x-4 > * {
                width: 100% !important;
                text-align: center !important;
                display: block !important;
            }

            .mobile-nav .space-x-4 a,
            .mobile-nav .space-x-4 span {
                display: block !important;
                width: 100% !important;
                padding: 0.5rem !important;
                margin: 0 !important;
            }

            .mobile-nav-buttons {
                flex-direction: column !important;
                gap: 0.75rem !important;
                width: 100% !important;
                align-items: center !important;
                display: flex !important;
            }

            .mobile-welcome {
                display: block !important;
                text-align: center !important;
                margin-bottom: 0 !important;
                padding: 0.5rem !important;
                background-color: #f8fafc !important;
                border-radius: 0.5rem !important;
                width: 100% !important;
            }

            .mobile-btn {
                display: block !important;
                width: 100% !important;
                text-align: center !important;
                padding: 0.75rem !important;
                margin: 0 !important;
                border-radius: 0.5rem !important;
            }
            
            .container {
                border-radius: 0;
            }
            
            .header {
                border-radius: 0;
                padding: 1rem;
            }
            
            .content {
                padding: 1rem;
            }
            
            .code-grid {
                grid-template-columns: 1fr;
            }
            
            .actions-row {
                flex-direction: column;
                align-items: stretch;
            }
            
            .btn {
                width: 100%;
                text-align: center;
            }
            
            th, td {
                padding: 0.5rem;
                font-size: 0.75rem;
            }
            
            .table-container {
                margin: 0 -1rem;
                border-radius: 0;
                border-left: none;
                border-right: none;
            }

            /* Improved hamburger menu positioning */
            #menu-toggle {
                top: 1rem !important;
                left: 1rem !important;
                width: 48px !important;
                height: 48px !important;
                z-index: 60 !important;
                transition: all 0.3s ease !important;
            }

            /* Hide hamburger menu when sidebar is active */
            #menu-toggle.sidebar-active {
                transform: translateX(-100%) !important;
                opacity: 0 !important;
                pointer-events: none !important;
            }

            /* Navigation container */
                    .mobile-nav-container {
            position: relative !important;
            z-index: 10 !important;
            clear: both !important;
            display: block !important;
            width: 100% !important;
            background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%) !important;
            border-bottom: 2px solid #bbf7d0 !important;
        }

            /* Mobile separator */
            .mobile-separator {
                height: 0.5rem !important;
                clear: both !important;
                display: block !important;
                width: 80% !important;
            }

            /* Ensure proper spacing on all mobile devices */
            /* Force main content layout */
            .main-content {
                margin-top: 2rem !important;
                padding-top: 1rem !important;
                position: relative !important;
                z-index: 1 !important;
                clear: both !important;
            }
            
            /* Prevent any overlapping */
            nav {
                position: relative !important;
                z-index: 10 !important;
                clear: both !important;
            }
            
            /* Force all elements to be block */
            .mobile-button-grid > * {
                display: block !important;
                width: 100% !important;
            }

            /* Prevent any floating elements */
            * {
                float: none !important;
            }

            /* Force proper stacking */
            .mobile-nav,
            .main-content,
            .mobile-button-grid {
                display: block !important;
                width: 100% !important;
                max-width:100% !important;
            }
        }
        
        /* Extra small mobile devices */
        @media (max-width: 480px) {
            .mobile-nav {
                padding: 0.75rem 0;
                gap: 0.75rem;
            }
            
            .mobile-nav h1 {
                font-size: 1.25rem;
            }
            
            .mobile-nav p {
                font-size: 0.875rem;
            }
            
            .mobile-btn {
                padding: 0.5rem;
                font-size: 0.875rem;
            }
            
            .mobile-welcome {
                font-size: 0.875rem;
                padding: 0.5rem;
            }

            .main-content {
                padding-top: 1rem !important;
            }
        }

        @media (max-width: 600px) {
            body {
                padding-top: 4.5rem; /* Adjust for smaller screens */
            }
            .codes-list { padding: 0.75rem; }
            .code-grid { grid-template-columns: 1fr !important; }
            .code-item { padding: 0.75rem; }
            .code-value { font-size: 1.1rem !important; padding: 0.5rem 0.75rem !important; }
            #copy-btn { font-size: 0.95rem !important; padding: 0.4rem 0.8rem !important; }
            .code-info { font-size: 0.9rem !important; }

            /* Adjust hamburger menu for very small screens */
            #menu-toggle {
                top: 0.75rem !important;
                left: 0.75rem !important;
                width: 44px !important;
                height: 44px !important;
            }

            /* Hide hamburger menu when sidebar is active on small screens */
            #menu-toggle.sidebar-active {
                transform: translateX(-100%) !important;
                opacity: 0 !important;
                pointer-events: none !important;
            }
        }
    </style>
</head>
<body class="bg-slate-50 min-h-screen">
    <!-- Navigation Bar -->
    <nav class="nav-green-theme shadow-sm mobile-nav-container">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center h-16 mobile-nav">
                <div class="flex items-center">
                    <img src="../assets/images/aimt-logo.png" alt="AIMT Logo" class="w-8 h-8 mr-3">
                    <div>
                        <h1 class="text-lg font-bold text-slate-900">Registration Code Generator</h1>
                        <p class="text-sm text-slate-500">Superadmin Portal</p>
                    </div>
                </div>
                <div class="flex items-center space-x-4 mobile-nav-buttons">
                    <span class="text-sm text-slate-600 mobile-welcome">Welcome, <?= htmlspecialchars($_SESSION['full_name'] ?? 'Superadmin') ?></span>
                    <a href="dashboard.php" class="bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 transition-colors text-sm mobile-btn">
                        Dashboard
                    </a>
                    <a href="../auth/logout.php" class="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition-colors text-sm mobile-btn">
                        Logout
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Clear separation -->
    <div class="mobile-separator"></div>
        <div class="flex-1">
            <div class="container">
                <div class="header">
                    <h2>Registration Code Generator</h2>
                </div>

                <div class="content">
                    <?php if (!empty($message) && $message_type !== 'success'): ?>
                        <div class="message <?php echo $message_type; ?>">
                            <?php echo htmlspecialchars($message); ?>
                        </div>
                    <?php endif; ?>

                    <?php if (!empty($generated_codes)): ?>
                        <div class="codes-list" style="margin-bottom:2rem;">
                            <div class="code-grid">
                                <div class="code-item" style="display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1rem;">
                                    <div style="display:flex;align-items:center;gap:0.5rem;">
                                        <svg width="32" height="32" fill="none" stroke="#10b981" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="16" cy="16" r="14" stroke="#10b981" stroke-width="2.5" fill="#e6f4ea"/><polyline points="23 11 15 19 11 15" stroke="#10b981" stroke-width="2.5"/></svg>
                                        <h3 style="margin:0;font-size:1.1rem;font-weight:600;color:#1e7e34;">Registration Code Generated!</h3>
                                    </div>
                                    <div style="display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap;">
                                        <span class="code-value" id="generated-code" style="font-size:1.5rem;padding:0.5rem 1.5rem;letter-spacing:2px;">
                                            <?php echo htmlspecialchars($generated_codes[0]['code']); ?>
                                        </span>
                                        <button class="btn btn-success" id="copy-btn" style="padding:0.5rem 1rem;font-size:1rem;">Copy</button>
                                    </div>
                                    <div class="code-info" style="width:100%;max-width:320px;">
                                        <div><span>Role:</span><span><b><?php echo ucfirst(htmlspecialchars($generated_codes[0]['role'])); ?></b></span></div>
                                        <?php if ($generated_codes[0]['specialization']): ?>
                                            <div><span>Specialization:</span><span><b><?php echo ucfirst(htmlspecialchars($generated_codes[0]['specialization'])); ?></b></span></div>
                                        <?php endif; ?>
                                        <div><span>Expires:</span><span><b><?php echo date('M j, Y', strtotime($generated_codes[0]['expiry_date'])); ?></b></span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <script>
                        document.addEventListener('DOMContentLoaded', function() {
                            var copyBtn = document.getElementById('copy-btn');
                            var codeSpan = document.getElementById('generated-code');
                            if(copyBtn && codeSpan) {
                                copyBtn.onclick = function() {
                                    var code = codeSpan.textContent.trim();
                                    navigator.clipboard.writeText(code).then(function() {
                                        copyBtn.textContent = 'Copied!';
                                        setTimeout(function(){ copyBtn.textContent = 'Copy'; }, 1500);
                                    });
                                };
                            }
                        });
                        </script>
                    <?php endif; ?>

                    <div class="info-card">
                        <h4>Code Format</h4>
                        <ul>
                            <li>4 characters (e.g., AB12, CD34)</li>
                            <li>Uppercase letters and numbers</li>
                            <li>Easy to type and remember</li>
                        </ul>
                    </div>

                    <div class="form-section">
                        <h3>Generate Code for User</h3>
                        <form action="" method="post" class="code-generation-form">
                            <div class="form-group">
                                <label for="role">Select User Type:</label>
                                <select id="role" name="role" required>
                                    <option value="">--Select User Type--</option>
                                    <option value="student">Student</option>
                                    <option value="technician">Technician</option>
                                    <option value="faculty">Faculty</option>
                                    <option value="nonteaching">Non-Teaching Staff</option>
                                    <option value="outsourced_vendor">Outsourced Vendor</option>
                                </select>
                            </div>

                            <div class="form-group" id="specialization-group" style="display: none;">
                                <label for="technician_spec">Specialization:</label>
                                <select id="technician_spec" name="technician_spec">
                                    <option value="">--Select Specialization--</option>
                                    <?php foreach (
                                        $categories as $cat): ?>
                                        <option value="<?php echo htmlspecialchars($cat); ?>">
                                            <?php echo ucfirst(htmlspecialchars($cat)); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="expiry_days">Expiry Period (days):</label>
                                <input type="number" id="expiry_days" name="expiry_days" min="1" max="365" value="30" required>
                                <small>Code will expire after the specified number of days</small>
                            </div>

                            <button type="submit" class="btn">Generate Code</button>
                        </form>
                    </div>

                    <div class="all-codes">
                        <div class="actions-row">
                            <h3>All Generated Codes</h3>
                            <a href="?download=true" class="btn btn-success">Download CSV</a>
                        </div>
                        
                        <div class="table-container">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Role</th>
                                        <th>Specialization</th>
                                        <th>Generated By</th>
                                        <th>Created Date</th>
                                        <th>Expiry Date</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($all_codes as $code): ?>
                                        <tr>
                                            <td class="code-cell"><?php echo htmlspecialchars($code['code']); ?></td>
                                            <td><?php echo ucfirst(htmlspecialchars($code['role'])); ?></td>
                                            <td><?php echo htmlspecialchars($code['specialization'] ?? 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($code['generated_by_username']); ?></td>
                                            <td><?php echo date('Y-m-d H:i', strtotime($code['created_at'])); ?></td>
                                            <td><?php echo date('Y-m-d H:i', strtotime($code['expiry_date'])); ?></td>
                                            <td class="<?php echo strtotime($code['expiry_date']) < time() ? 'status-expired' : 'status-active'; ?>">
                                                <?php echo strtotime($code['expiry_date']) < time() ? 'Expired' : 'Active'; ?>
                                            </td>
                                            <td>
                                                <a href="?delete=<?php echo urlencode($code['code']); ?>" 
                                                   class="btn btn-danger" 
                                                   onclick="return confirm('Are you sure you want to delete this code?');">
                                                    Delete
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="back-btn">
                        <a href="dashboard.php" class="btn btn-secondary">Back to Dashboard</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('role').addEventListener('change', function() {
            const specGroup = document.getElementById('specialization-group');
            const specSelect = document.getElementById('technician_spec');
            // Hide specialization for technician
            if (this.value === 'technician') {
                specGroup.style.display = 'none';
                specSelect.required = false;
                specSelect.value = '';
            } else {
                specGroup.style.display = 'none'; // Hide for all roles for now
                specSelect.required = false;
                specSelect.value = '';
            }
        });

        // Mobile menu toggle functionality
        document.addEventListener('DOMContentLoaded', () => {
            const menuToggle = document.getElementById('menu-toggle');
            const sidebar = document.querySelector('.sidebar');
            const sidebarOverlay = document.getElementById('sidebar-overlay');
            
            function toggleMobileMenu() {
                const isActive = sidebar.classList.contains('hidden');
                
                if (isActive) {
                    // Open menu
                    sidebar.classList.remove('hidden');
                    sidebarOverlay.classList.remove('hidden');
                    menuToggle.classList.add('sidebar-active');
                    document.body.style.overflow = 'hidden';
                } else {
                    // Close menu
                    sidebar.classList.add('hidden');
                    sidebarOverlay.classList.add('hidden');
                    menuToggle.classList.remove('sidebar-active');
                    document.body.style.overflow = '';
                }
            }
            
            menuToggle.addEventListener('click', (e) => {
                e.stopPropagation();
                toggleMobileMenu();
            });

            // Close sidebar when clicking overlay
            sidebarOverlay.addEventListener('click', () => {
                toggleMobileMenu();
            });

            // Close sidebar when clicking outside
            document.addEventListener('click', (event) => {
                if (window.innerWidth <= 768 && 
                    !sidebar.contains(event.target) && 
                    !menuToggle.contains(event.target) && 
                    !sidebar.classList.contains('hidden')) {
                    toggleMobileMenu();
                }
            });

            // Handle window resize
            window.addEventListener('resize', () => {
                if (window.innerWidth > 768) {
                    sidebar.classList.add('hidden');
                    sidebarOverlay.classList.add('hidden');
                    menuToggle.classList.remove('sidebar-active');
                    document.body.style.overflow = '';
                }
            });

            // Close menu when pressing Escape key
            document.addEventListener('keydown', (event) => {
                if (event.key === 'Escape' && !sidebar.classList.contains('hidden')) {
                    toggleMobileMenu();
                }
            });
        });
    </script>
</body>
</html>
